# Generated by Django 2.2.24 on 2021-11-17 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_options_questionoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='question_id',
        ),
        migrations.AddField(
            model_name='answers',
            name='question_option_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_question_option_id', to='questions.QuestionOptions'),
        ),
    ]
